### ISSUE TITLE
Missing Elements in the MenuBar when extending from JFrame

### ISSUE THREAD

**Issue by CommentSectionScientist** [weisJ/darklaf#129]
If the class itself is a JFrame, the minimize, maximize, close, buttons and the symbol go missing.

Code from the example, changed so that DarklafDemo itself is a JFrame:
```
public class DarklafDemo extends JFrame {

	public static void main(final String[] args) {
		SwingUtilities.invokeLater(() -> {
			new DarklafDemo();
		});
	}

	public DarklafDemo() {
		LafManager.install(new SolarizedDarkTheme());

		setTitle("Darklaf - A themeable LaF for Swing");
		setSize(600, 400);

		JButton button = new JButton("Click here!");

		JPanel content = new JPanel();
		content.add(button);

		setLocationRelativeTo(null);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setContentPane(content);
		setVisible(true);
	}
}
```
![grafik](https://user-images.githubusercontent.com/36775764/78507167-bf763080-777e-11ea-897a-afe26ee4a2a4.png)

What if should look like:
![grafik](https://user-images.githubusercontent.com/36775764/78507215-1bd95000-777f-11ea-8333-6baf72db0581.png)

EDIT:
Looks like the problem is, that the Laf is installed after the JFrame object creation.
If you change the code from the example and switch the two lines, so that the object is created before the LafManager install call, the Buttons are missing aswell.
```
JFrame frame = new JFrame("Darklaf - A themeable LaF for Swing");
LafManager.install();
```

**Comment by weisJ** [comment]
The problem here is that whatever Laf is installed before calling`LafManager.install()` (`WindowsLookAndFeel` in this case) does not specify that it provides decorations i.e. `JFrame#isDefaultLookAndFeelDecorated` returns `false`. Now `JFrame` and co. all populate `rootPane#setWindowDecorationStyle` in their constructor with a check for 'JFrame#isDefaultLookAndFeelDecorated'. Now if the frame gets created before the laf is installed the decorations style property of the rootpane will always be `NONE` thus no buttons on the frame.

Now one option would be to always use `JRootPane.FRAME` if the windows is a `JFrame` but this approach assumes that no `JFrame` would have a different decorations style. :(
