### ISSUE TITLE
Feature request: TextField input prompt

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#143]
As there is no default input prompt property for text fields in swing, would it be nice to have a simple function to set one, without using `FocusListener` or similar.

**Comment by weisJ** [comment]
Could you please elaborate what you exactly mean by this. Is this purely cosmetic or also behavioural?

**Comment by vlsi** [comment]
I guess the feature is called "input placeholder": https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder , https://css-tricks.com/almanac/selectors/p/placeholder/#article-header-id-1 and so on.

That is darklaf should render a pre-defined text when the input is empty.
The placeholder text could be configured with a client property.

**Comment by weisJ** [comment]
Ok. This shouldn't be too much effort.

**Comment by weisJ** [comment]
@GraxCode is this what you had in mind?
![default_text_field](https://user-images.githubusercontent.com/31143295/79978213-d8315680-849f-11ea-92bc-70b2f4f483bc.gif)

**Comment by vlsi** [comment]
Could you please make so that a focused empty element is still rendered with a placeholder?

See sample in https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder

**Comment by weisJ** [comment]
Yes. To use simply provide
````
comp.putClientProperty(DarkTextUI.KEY_DEFAULT_TEXT, "Your default text");
````
The effect works with all `JTextComponent` variants though the default text is not respected when calculating the preferred size (Not sure whether it should). Also it won't adhere to some formatting of component which have multi-line support (You can achieve it using html text with manual linebreaks, but make sure that it actually fits).

These limitations are due to the renderer of the default text for the moment always being a ``JLabel`. If I have an idea how to support the various `View`s of other components I will add them.

**Comment by GraxCode** [comment]
That's exactly what i had in mind! Nice!

**Comment by weisJ** [comment]
Available with the next release.
