### ISSUE TITLE
[JTable] TableCellRenderer behaviour different to vanilla swing

### ISSUE THREAD

**Issue by tychobrailleur** [weisJ/darklaf#164]
**Describe the bug**
When setting a `TableCellRenderer` for `Object.class` and that the model returns class `java.lang.String` (for example), the renderer does not revert to the default `Object` renderer:

![Screenshot 2020-05-04 at 13 09 59](https://user-images.githubusercontent.com/114285/80964678-3697f680-8e09-11ea-8ab1-71801bc0e4b9.png)

This differs in behaviour from plain Swing where the `Object` renderer is used if no renderer for `String` has been set:

![Screenshot 2020-05-04 at 13 10 17](https://user-images.githubusercontent.com/114285/80964932-9e4e4180-8e09-11ea-84ff-88d1454b69af.png)

Getting around the issue is [straightforward enough for my case](https://github.com/tychobrailleur/HO/commit/8f6e2a5e10a57473f3cb2cc2922b335ea9174ded#diff-fad169c2bd66e6d2c353c14e4ddc880bR146) (defining the renderer for the specific type), but this behaviour change may cause issues for people adopting darklaf.

**To Reproduce**
See https://gist.github.com/tychobrailleur/3bbde9442bfd2615049c1968723f6f3b
Commenting out the `LafManager.install(new DarculaTheme());` line causes the `DarkTableCellRenderer` to be used.

**Screenshots**
See above

**Additional Information:**
 - OS: macOS
 - OS Version: 10.14.6
- Darklaf Version: 2.1.1

**Additional context**
N/A

**Comment by weisJ** [comment]
This is because the renderer is set for most classes separately. I think at one point I planned to have separate renderers but never actually implemented them. I can change it so only `Object.class` is associated.

One suggestion though. In my opinion implementing a custom `*CellRenderer` by overriding `Default*CellRenderer` is really bad practice. Especially if you only want to change minor things as borders etc. My approach would by to use a wrapper class using the default renderer of the Laf as a base. Something like this:
````java
public class TableCellRendererDelegate implements TableCellRenderer {
    
    private final TableCellRenderer renderer;

    public TableCellRendererDelegate(TableCellRenderer renderer) {
        this.renderer = renderer;
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component comp = renderer.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        // Customizations here
        return comp;
    }
}
````
````java
        table.setDefaultRenderer(Object.class, new TableCellRendererDelegate(table.getDefaultRenderer(Object.class)));
````
This offers a LaF agnostic way of modifying the renderer component without losing consistency with other tables that use the renderer provided by the Laf.

For example (This is with alternating row background enabled. The default on macOS):
With default laf renderer:
| | |
|:-:|:-:|
|![table_default](https://user-images.githubusercontent.com/31143295/81091659-d20b9300-8eff-11ea-8452-ac5f7a2ecb69.png)|![table_default_light](https://user-images.githubusercontent.com/31143295/81091976-3d556500-8f00-11ea-99f5-1e300c0d48f3.png)|

With custom renderer extending `DefaultTableCellRenderer`:
| | |
|:-:|:-:|
|![table_custom_dark](https://user-images.githubusercontent.com/31143295/81091705-e2237280-8eff-11ea-8754-24ea862566c8.png)|![table_custom_light](https://user-images.githubusercontent.com/31143295/81091755-f23b5200-8eff-11ea-8091-26dfa2ad6a61.png)|

With custom renderer using a delegate:
| | |
|:-:|:-:|
|![table_delegate_dark](https://user-images.githubusercontent.com/31143295/81091811-054e2200-8f00-11ea-85d5-58227002beec.png)|![table_delegate_light](https://user-images.githubusercontent.com/31143295/81091847-11d27a80-8f00-11ea-9a48-a177de18cc81.png)|

**Comment by tychobrailleur** [comment]
> This is because the renderer is set for most classes separately. I think at one point I planned to have separate renderers but never actually implemented them. I can change it so only `Object.class` is associated.

This obviously depends on the backward compatibility requirements for darklaf, but this would be the least surprising behaviour for a developer migrating from vanilla Swing.

From my perspective, documenting the behaviour difference would be enough.

> 
> One suggestion though. In my opinion implementing a custom `*CellRenderer` by overriding `Default*CellRenderer` is really bad practice. Especially if you only want to change minor things as borders etc. 

Yes, agreed, the decorator approach is quite neat.  Unfortunately codebases out there (including HO) are a lot more complex than my little repro class, and tend to implement `TableCellRenderer` (probably because lots of swing tutorials promote that approach). ;-)
