### ISSUE TITLE
[macOS] Tooltip is opaque

### ISSUE THREAD

**Issue by kirill-grouchnikov** [weisJ/darklaf#180]
This is under the latest 2.2.2

```java
public class Test {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            LafManager.install();

            JFrame frame = new JFrame("Test");
            frame.setLayout(new FlowLayout());
            JButton button = new JButton("test");
            button.setToolTipText("tooltip");
            frame.add(button);

            frame.setSize(600, 300);
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.setVisible(true);
        });
    }
}
```

<img width="243" alt="Screen Shot 2020-06-10 at 11 38 11 AM" src="https://user-images.githubusercontent.com/52874/84288322-054ccd80-ab0f-11ea-9b47-69c173bfa73a.png">

**Comment by x4e** [comment]
@weisJ This bug seems to still be appearing on Linux.
![image](https://user-images.githubusercontent.com/53862811/100724186-8304de00-33ba-11eb-83c8-705199ba6514.png)

I'm on Arch Linux x86_64 (5.9.8-arch1-1).

It also seems to be incredibly hard to activate tooltips. They don't appear after hovering, but can in some circumstances be triggered with control + f1, however this is very hard to trigger.
