### ISSUE TITLE
Wrong hit area in JCheckBoxList

### ISSUE THREAD

**Issue by nightm4re94** [weisJ/darklaf#190]
**Describe the bug**
The currently focused JCheckBox in a JCheckBoxList cannot be clicked correctly since it is automatically offset to the right.
The offset is just visual: the boundaries that register mouse clicks stay in the same position, hence it is only possible to activate the checkbox when clicking outside of it.

**To Reproduce**
For me, the problem came up with the most basic configuration: Initialize a JCheckBoxList and assign a DefaultListModel to it.
```java 
    DefaultListModel<JCheckBox> layerModel = new DefaultListModel<>();
    JCheckBoxList list = new JCheckBoxList();
    list.setModel(layerModel);
```

**Screenshots**
![checkboxlist](https://user-images.githubusercontent.com/26114385/86157457-b68bc580-bb07-11ea-91fc-d795354b2f58.gif)

**Additional Information:**
 - OS: Windows 10
- Darklaf Version: [e.g. 2.1.1]

**Comment by weisJ** [comment]
I guess there is a conflict, where the checkbox adjusts it's size because it is inside a cell renderer. Is the checkbox supposed to be further to the right when it is focused? It looks like the hit area aligns with the bounds of the non-focused checkboxes. If not this may be a painting issue.

Could you also provide the source code for the `JCheckBoxList` you are using as it isn't a standard component?

**Comment by nightm4re94** [comment]
Oh god, this is embarrassing - I forgot that the `JCheckBoxList` was actually a custom component.
We had once written some custom border behaviour for it, but that was incompatible with darklaf defaults.
After removing the custom behaviour it worked!
