### ISSUE TITLE
Unable to select element in JTree if it has been highlighted

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#195]
**Describe the bug**
Using nightly build of JMeter
Open JMeter
Templates > Build a Web Tes Plan > Create
Select HTTP Request Defaults
CTRL+F
Enter Scenario in Search
Click Search All 
Try to select Scenario 1, impossible

**Screenshots**

Notice also strange duplication, it's on another Test Plan but will happen with described scenario:

<img width="234" alt="BUG_DARKLAF_UNABLE_TO_SELECT" src="https://user-images.githubusercontent.com/3127467/88403872-65e94e80-cdcd-11ea-827a-e3f677d5e132.PNG">

**Additional Information:**
 - OS: Windows 10
 - OS Version: 10
- Darklaf Version: 2.4.1

**Comment by pmouawad** [comment]
Hello @weisJ ,
It appears issue is a regression , it was not present in 2.1.1.
It also happens on MacOSX

Regards

**Comment by weisJ** [comment]
I think I know what is causing the issue but I'll have to investigate a bit further.
For now I see a few more issues in the image:
- Blue and red border around the items come from the default cell renderer. This shouldn't be the case.
- The cell popup seems to be visible, even though the cell isn't obscured. It's also at an incorrect location.

**Comment by weisJ** [comment]
Ok I think I see what is happening here. In which way do you highlight the search results?

**Comment by weisJ** [comment]
I could resolve the issue by replacing the border declaration in `JMeterCellRenderer` with
````java
private static final Border RED_BORDER = BorderFactory.createCompoundBorder(
       BorderFactory.createLineBorder(Color.red),
       BorderFactory.createEmptyBorder(-1, -1, -1, -1) // Remove the insets from the line border resulting in 0 insets.
);
private static final Border BLUE_BORDER = BorderFactory.createCompoundBorder(
       BorderFactory.createLineBorder(Color.blue),
       BorderFactory.createEmptyBorder(-1, -1, -1, -1)
);
````
When calculating whether the tree hint should be shown the renderer reported a height of `21` while the cell only has a height of `20` resulting in weird popup positioning for the hint. Because the popup was being overlayed over the actual cell it couldn't be pressed.

I have also adjusted the code calculating the preferred cell size on my end to account for borders, so it works without the above adjustments. 

However with the way the borders are declared currently a small movement in cell position is noticeable (in all LaFs). Because the border is used as an overlay marker I would recommend it not having any non-zero insets.

**Comment by pmouawad** [comment]
Hello @weisJ ,
Thanks for analysis.
Is the issue fixed by https://github.com/weisJ/darklaf/commit/2234c0dd20e68ce49b1fefba9f85f39a4667b4c8 ? 
without changing our code ? 

It's not clear for me.

Thank you

**Comment by weisJ** [comment]
Yes that should be the case.

**Comment by pmouawad** [comment]
I confirmed that issue is fixed 👍 
But can you clarify what's the effect of:
_However with the way the borders are declared currently a small movement in cell position is noticeable (in all LaFs). Because the border is used as an overlay marker I would recommend it not having any non-zero insets._


When do you plan a minor version release ? 
Thanks

**Comment by weisJ** [comment]
> But can you clarify what's the effect of this by showing a screenshot for example :
> _However with the way the borders are declared currently a small movement in cell position is noticeable (in all LaFs). Because the border is used as an overlay marker I would recommend it not having any non-zero insets.

Here is a comparison of the tree cells with and without the border:
![border_1](https://user-images.githubusercontent.com/31143295/88784016-cee71280-d18f-11ea-9a16-b4af837d60da.png)

It's not a huge difference but still visible (you may have to zoom in). The text is slightly shifted to the right because the border takes up space. Especially at the time the border is applied the shift is noticeable. My proposed change would be to use borders that have insets with `0` size.

**Comment by weisJ** [comment]
> When do you plan a minor version release ?

If you can verify that #196 is fixed for you I'll release the next version.
