### ISSUE TITLE
MacOS notarization fails when Darklaf is included

### ISSUE THREAD

**Issue by Syer10** [weisJ/darklaf#301]
**Describe the bug**
I use Compose for Desktop to build a desktop app, for the window decorations and Swing components I have Darklaf. After the update that added ARM64 support I noticed that apple notarization was failing.

**To Reproduce**
Make an empty Compose for Desktop project using IntelliJ(New project -> Kotlin -> Compose Desktop Application), implement Darklaf, and follow the [notarization guide](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Signing_and_notarization_on_macOS). You should get an email saying notarization failed and then you can see why it failed by running the checkNotarizationStatus task

**Screenshots**
If applicable, add screenshots to help explain your problem. Visual material should only be used in assistance
to the description of the Bug and **does not** replace it.

**Additional Information:**
 - OS: macOS
 - OS Version: Any
- Darklaf Version: v2.7.3 

**Additional context**
Here is part of the json that apple sent me in response to notarization failing
```json
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "Tachidesk-JUI-1.2.1.dmg/Tachidesk-JUI.app/Contents/app/darklaf-macos-2.7.3-b2f262cae97e521eb9275bb369edace.jar/com/github/weisj/darklaf/platform/darklaf-macos/JavaNativeFoundation.framework/JavaNativeFoundation",
      "message": "The signature of the binary is invalid.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Tachidesk-JUI-1.2.1.dmg/Tachidesk-JUI.app/Contents/app/darklaf-macos-2.7.3-b2f262cae97e521eb9275bb369edace.jar/com/github/weisj/darklaf/platform/darklaf-macos/JavaNativeFoundation.framework/JavaNativeFoundation",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Tachidesk-JUI-1.2.1.dmg/Tachidesk-JUI.app/Contents/app/darklaf-macos-2.7.3-b2f262cae97e521eb9275bb369edace.jar/com/github/weisj/darklaf/platform/darklaf-macos/JavaNativeFoundation.framework/JavaNativeFoundation",
      "message": "The signature of the binary is invalid.",
      "docUrl": null,
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "Tachidesk-JUI-1.2.1.dmg/Tachidesk-JUI.app/Contents/app/darklaf-macos-2.7.3-b2f262cae97e521eb9275bb369edace.jar/com/github/weisj/darklaf/platform/darklaf-macos/JavaNativeFoundation.framework/JavaNativeFoundation",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "arm64"
    }
```

**Comment by weisJ** [comment]
Simple answer: macOS no longer ships `JavaNativeFoundation` as a system framework hence I had to include a build myself in the jar. Notably I don't own a mac myself and am not enrolled in the developer program. This makes it impossible for me to sign the framework. The best I can offer is to try to get rid of the framework entirely and statically compile it into the dynamic library. Not sure whether that solves your problem though. Do dynamic libraries need to be signed too?

For now I would suggest to do the following:
- Extract the `JavaNativeFoundation` file from the `darklaf-macos` jar.
- Codesign it yourself (I assume you do have a codesign identitiy)
- Repackage the jar to be included in the build.

Alternatively: Fork `https://github.com/weisJ/JavaNativeFoundation` and publish a version, which is codesigned using your signature to maven central. I'll then be able to include it in the build instead of the unsigned version.

**Comment by Syer10** [comment]
For signing the person building the app needs to sign every lib with their own codesigning key. I believe that `.dylib` and `.jnilib` files are automatically signed with their key by Compose for Desktop. If you can make it one of those files it should sign it automatically.

**Comment by Syer10** [comment]
Otherwise I can take a look to see if I can sign it on my own, Compose for Desktop takes over the signing and building responsibility and I would not be too sure how to I would go about signing files during its build.

**Comment by weisJ** [comment]
I’m currently trying to statically compile the JavaNativeFoundation into the darklaf libraries, but I am facing some troubles. I have two ideas on how to do this:
1. Copy the content of https://github.com/apple/openjdk/tree/xcodejdk14-release/apple/JavaNativeFoundation/JavaNativeFoundation into this repository and compile it with the library (this is essentially what I tried in #302. However compilation seems to be failing due to differences in the compiler setup.
2. Compile https://github.com/weisJ/JavaNativeFoundation as a static library instead of a framework and consume it from here.

Ideally I’d like to get 2. to be working. In both cases the development cycle is rather time consuming for me as I’m only able to get feedback by pushing the changes and waiting for the action output. I’d really appreciate any help here (for either option).

**Comment by weisJ** [comment]
Please try whether this version works for you:
````kotlin
repositories {
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}
configurations.all {
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}
dependencies {
    implementation("com.github.weisj:darklaf-core-jnf:latest.integration")
}
````

**Comment by Syer10** [comment]
It works perfect! It notarizes fine and the window looks good. I don't see any issues in my application

**Comment by weisJ** [comment]
Wonderful :)
